### ISSUE TITLE
Set SN_MVA = 1

### ISSUE THREAD

**Issue by vogt31337** [e2nIEE/pandapower-qgis#6]
Hi,

pandapower normally expects an sn_mva = 1, currently it is configurable and set to 1000.
Just remove the box and set it straight to one.

BR

**Comment by KS-HTK** [comment]
This issue came straight from pandapower documentation:
https://pandapower.readthedocs.io/en/v2.10.1/elements/empty_network.html

> pandapower.create_empty_network(name='', f_hz=50.0, sn_mva=1, add_stdtypes=True)
has correct `sn_mva=1` but the description lists
> sn_mva (float, 1e3) - reference apparent power for per unit system
which has default value set to `1e3`

maybe forwarding this issue is a good idea.
